
package sig3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-10-14T13:45:49.397+02:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "Exception", targetNamespace = "http://sig3/")
public class Exception_Exception extends java.lang.Exception {
    
    private sig3.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, sig3.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, sig3.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public sig3.Exception getFaultInfo() {
        return this.exception;
    }
}
