package sig3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-10-15T13:15:30.948+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://sig3/", name = "WS2Service")
@XmlSeeAlso({ObjectFactory.class})
public interface WS2Service {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotes", targetNamespace = "http://sig3/", className = "sig3.GetTotes")
    @WebMethod
    @ResponseWrapper(localName = "getTotesResponse", targetNamespace = "http://sig3/", className = "sig3.GetTotesResponse")
    public java.util.List<sig3.Person> getTotes();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUnidad", targetNamespace = "http://sig3/", className = "sig3.GetUnidad")
    @WebMethod
    @ResponseWrapper(localName = "getUnidadResponse", targetNamespace = "http://sig3/", className = "sig3.GetUnidadResponse")
    public sig3.Unidad getUnidad(
        @WebParam(name = "codi", targetNamespace = "")
        java.lang.String codi
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCodigoPuestos", targetNamespace = "http://sig3/", className = "sig3.GetCodigoPuestos")
    @WebMethod
    @ResponseWrapper(localName = "getCodigoPuestosResponse", targetNamespace = "http://sig3/", className = "sig3.GetCodigoPuestosResponse")
    public java.util.List<java.lang.String> getCodigoPuestos();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPuesto", targetNamespace = "http://sig3/", className = "sig3.GetPuesto")
    @WebMethod
    @ResponseWrapper(localName = "getPuestoResponse", targetNamespace = "http://sig3/", className = "sig3.GetPuestoResponse")
    public sig3.Puesto getPuesto(
        @WebParam(name = "codi", targetNamespace = "")
        java.lang.String codi
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotesByCognom", targetNamespace = "http://sig3/", className = "sig3.GetTotesByCognom")
    @WebMethod
    @ResponseWrapper(localName = "getTotesByCognomResponse", targetNamespace = "http://sig3/", className = "sig3.GetTotesByCognomResponse")
    public java.util.List<sig3.Person> getTotesByCognom(
        @WebParam(name = "cognom", targetNamespace = "")
        java.lang.String cognom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCodigoUnidades", targetNamespace = "http://sig3/", className = "sig3.GetCodigoUnidades")
    @WebMethod
    @ResponseWrapper(localName = "getCodigoUnidadesResponse", targetNamespace = "http://sig3/", className = "sig3.GetCodigoUnidadesResponse")
    public java.util.List<java.lang.String> getCodigoUnidades();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDadesPersona", targetNamespace = "http://sig3/", className = "sig3.GetDadesPersona")
    @WebMethod
    @ResponseWrapper(localName = "getDadesPersonaResponse", targetNamespace = "http://sig3/", className = "sig3.GetDadesPersonaResponse")
    public sig3.Person getDadesPersona(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
