package sig3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-10-15T13:15:30.958+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "WS2ServiceService", 
                  wsdlLocation = "http://localhost:8099/SIG3/services/WS2?wsdl",
                  targetNamespace = "http://sig3/") 
public class WS2ServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sig3/", "WS2ServiceService");
    public final static QName WS2ServicePort = new QName("http://sig3/", "WS2ServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8099/SIG3/services/WS2?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WS2ServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8099/SIG3/services/WS2?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WS2ServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WS2ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WS2ServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WS2ServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WS2ServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WS2ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WS2Service
     */
    @WebEndpoint(name = "WS2ServicePort")
    public WS2Service getWS2ServicePort() {
        return super.getPort(WS2ServicePort, WS2Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WS2Service
     */
    @WebEndpoint(name = "WS2ServicePort")
    public WS2Service getWS2ServicePort(WebServiceFeature... features) {
        return super.getPort(WS2ServicePort, WS2Service.class, features);
    }

}
