package sig3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-10-15T13:15:31.173+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://sig3/", name = "WSFileService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSFileService {

    @WebResult(name = "obtenirPDFReturn", targetNamespace = "")
    @RequestWrapper(localName = "obtenirPDF", targetNamespace = "http://sig3/", className = "sig3.ObtenirPDF")
    @WebMethod
    @ResponseWrapper(localName = "obtenirPDFResponse", targetNamespace = "http://sig3/", className = "sig3.ObtenirPDFResponse")
    public sig3.ContenidorPDF obtenirPDF(
        @WebParam(name = "dataFitxer", targetNamespace = "")
        java.lang.String dataFitxer,
        @WebParam(name = "IDEmpleat", targetNamespace = "")
        java.lang.String idEmpleat
    );
}
