package sig3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-10-15T13:15:30.368+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://sig3/", name = "WSPruebaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WSPruebaServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotsPernrByCognom", targetNamespace = "http://sig3/", className = "sig3.GetTotsPernrByCognom")
    @WebMethod
    @ResponseWrapper(localName = "getTotsPernrByCognomResponse", targetNamespace = "http://sig3/", className = "sig3.GetTotsPernrByCognomResponse")
    public java.util.List<java.lang.String> getTotsPernrByCognom(
        @WebParam(name = "cognom", targetNamespace = "")
        java.lang.String cognom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDadesPersona", targetNamespace = "http://sig3/", className = "sig3.GetDadesPersona")
    @WebMethod
    @ResponseWrapper(localName = "getDadesPersonaResponse", targetNamespace = "http://sig3/", className = "sig3.GetDadesPersonaResponse")
    public sig3.Person getDadesPersona(
        @WebParam(name = "codi", targetNamespace = "")
        java.lang.String codi
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "dummy", targetNamespace = "http://sig3/", className = "sig3.Dummy")
    @WebMethod
    @ResponseWrapper(localName = "dummyResponse", targetNamespace = "http://sig3/", className = "sig3.DummyResponse")
    public java.lang.String dummy();
}
