package sig3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-10-15T13:15:30.546+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "WSPruebaService", 
                  wsdlLocation = "http://localhost:8099/SIG3/services/WSPrueba?wsdl",
                  targetNamespace = "http://sig3/") 
public class WSPruebaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sig3/", "WSPruebaService");
    public final static QName WSPruebaServicePort = new QName("http://sig3/", "WSPruebaServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8099/SIG3/services/WSPrueba?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSPruebaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8099/SIG3/services/WSPrueba?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSPruebaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSPruebaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSPruebaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPruebaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPruebaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPruebaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSPruebaServicePortType
     */
    @WebEndpoint(name = "WSPruebaServicePort")
    public WSPruebaServicePortType getWSPruebaServicePort() {
        return super.getPort(WSPruebaServicePort, WSPruebaServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSPruebaServicePortType
     */
    @WebEndpoint(name = "WSPruebaServicePort")
    public WSPruebaServicePortType getWSPruebaServicePort(WebServiceFeature... features) {
        return super.getPort(WSPruebaServicePort, WSPruebaServicePortType.class, features);
    }

}
