package edu.upc.spa.rebutnomina;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-11-27T09:48:19.463+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "ZHRPORTALREBUTNOMINAV1", 
                  wsdlLocation = "https://bus-soades.upc.edu/SPA/RebutNominav1?wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZHRPORTALREBUTNOMINAV1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZHRPORTALREBUTNOMINAV1");
    public final static QName ZHRPORTALREBUTNOMINAV1 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZHRPORTALREBUTNOMINAV1");
    static {
        URL url = null;
        try {
            url = new URL("https://bus-soades.upc.edu/SPA/RebutNominav1?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZHRPORTALREBUTNOMINAV1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://bus-soades.upc.edu/SPA/RebutNominav1?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZHRPORTALREBUTNOMINAV1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZHRPORTALREBUTNOMINAV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZHRPORTALREBUTNOMINAV1() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZHRPORTALREBUTNOMINAV1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZHRPORTALREBUTNOMINAV1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZHRPORTALREBUTNOMINAV1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZHRWSREBUTNOMINA
     */
    @WebEndpoint(name = "ZHRPORTALREBUTNOMINAV1")
    public ZHRWSREBUTNOMINA getZHRPORTALREBUTNOMINAV1() {
        return super.getPort(ZHRPORTALREBUTNOMINAV1, ZHRWSREBUTNOMINA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZHRWSREBUTNOMINA
     */
    @WebEndpoint(name = "ZHRPORTALREBUTNOMINAV1")
    public ZHRWSREBUTNOMINA getZHRPORTALREBUTNOMINAV1(WebServiceFeature... features) {
        return super.getPort(ZHRPORTALREBUTNOMINAV1, ZHRWSREBUTNOMINA.class, features);
    }

}
