package edu.upc.spa.rebutnomina;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import edu.upc.spa.utils.WSSUtilities;

/**
 * This class was generated by Apache CXF 2.4.2 2014-11-27T09:48:19.396+01:00
 * Generated source version: 2.4.2
 * 
 */
public final class ZHRWSREBUTNOMINA_ZHRPORTALREBUTNOMINAV1_Client {

	private static final QName SERVICE_NAME = new QName(
			"urn:sap-com:document:sap:soap:functions:mc-style",
			"ZHRPORTALREBUTNOMINAV1");

	private ZHRWSREBUTNOMINA_ZHRPORTALREBUTNOMINAV1_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = ZHRPORTALREBUTNOMINAV1.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ZHRPORTALREBUTNOMINAV1 ss = new ZHRPORTALREBUTNOMINAV1(wsdlURL,
				SERVICE_NAME);
		ZHRWSREBUTNOMINA port = ss.getZHRPORTALREBUTNOMINAV1();

		try {
			WSSUtilities.afegirUsernameTokenPeticioSOAP(port, "intranet.servei.personal", "laura1laura1");
		} catch (Exception e) {
			// Tratamiento de la excepción
		}

		{
			System.out.println("Invoking zhrPortalNouRebutNomina...");
			java.lang.String _zhrPortalNouRebutNomina_period = "201305";
			java.lang.String _zhrPortalNouRebutNomina_pernr = "00000015";
			javax.xml.ws.Holder<edu.upc.spa.rebutnomina.ZhrPortalNouErrorsTable> _zhrPortalNouRebutNomina_missatges = new javax.xml.ws.Holder<edu.upc.spa.rebutnomina.ZhrPortalNouErrorsTable>();
			javax.xml.ws.Holder<byte[]> _zhrPortalNouRebutNomina_pdf = new javax.xml.ws.Holder<byte[]>();
			port.zhrPortalNouRebutNomina(_zhrPortalNouRebutNomina_period,
					_zhrPortalNouRebutNomina_pernr,
					_zhrPortalNouRebutNomina_missatges,
					_zhrPortalNouRebutNomina_pdf);

			System.out
					.println("zhrPortalNouRebutNomina._zhrPortalNouRebutNomina_missatges="
							+ _zhrPortalNouRebutNomina_missatges.value);
			System.out
					.println("zhrPortalNouRebutNomina._zhrPortalNouRebutNomina_pdf="
							+ _zhrPortalNouRebutNomina_pdf.value);

		}

		System.exit(0);
	}

}
