
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edu.upc.spa.rebutnomina;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-11-27T09:48:19.445+01:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZHRPORTALREBUTNOMINAV1",
                      portName = "ZHRPORTALREBUTNOMINAV1",
                      targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                      wsdlLocation = "https://bus-soades.upc.edu/SPA/RebutNominav1?wsdl",
                      endpointInterface = "edu.upc.spa.rebutnomina.ZHRWSREBUTNOMINA")
                      
public class ZHRWSREBUTNOMINAImpl implements ZHRWSREBUTNOMINA {

    private static final Logger LOG = Logger.getLogger(ZHRWSREBUTNOMINAImpl.class.getName());

    /* (non-Javadoc)
     * @see edu.upc.spa.rebutnomina.ZHRWSREBUTNOMINA#zhrPortalNouRebutNomina(java.lang.String  period ,)java.lang.String  pernr ,)edu.upc.spa.rebutnomina.ZhrPortalNouErrorsTable  missatges ,)byte[]  pdf )*
     */
    public void zhrPortalNouRebutNomina(java.lang.String period,java.lang.String pernr,javax.xml.ws.Holder<ZhrPortalNouErrorsTable> missatges,javax.xml.ws.Holder<byte[]> pdf) { 
        LOG.info("Executing operation zhrPortalNouRebutNomina");
        System.out.println(period);
        System.out.println(pernr);
        try {
            edu.upc.spa.rebutnomina.ZhrPortalNouErrorsTable missatgesValue = null;
            missatges.value = missatgesValue;
            byte[] pdfValue = new byte[0];
            pdf.value = pdfValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
